DROP TABLE CALBOARD;
DROP SEQUENCE CALBOARDSEQ;

CREATE SEQUENCE CALBOARDSEQ;
CREATE TABLE CALBOARD(

	CAL_NO NUMBER PRIMARY KEY,
	USER_NO NUMBER NOT NULL,
	CAL_TITLE VARCHAR2(2000) NOT NULL,
	CAL_CONTENT VARCHAR2(4000) NOT NULL,
	CAL_MDATE VARCHAR2(12) NOT NULL, 		--12자리로 만듬
	CAL_REGDATE DATE NOT NULL,
	CONSTRAINT CAL_UN_FK FOREIGN KEY(USER_NO) REFERENCES USER_INFO(USER_NO)
);

SELECT *
FROM user_info;

INSERT INTO CALBOARD
VALUES(CALBOARDSEQ.NEXTVAL,'3','토익 영단어','500개 달성이 목표','20201115',SYSDATE);

INSERT INTO CALBOARD
VALUES(CALBOARDSEQ.NEXTVAL,'3','연회 알바','오전 10시~오후 8시까지 근무','20201116',SYSDATE);


INSERT INTO CALBO ARD
VALUES(CALBOARDSEQ.NEXTVAL,'3','Kh정보교육원 수료','프로젝트 발표 및 수료식/ 이후 회식있음 ','20201117',SYSDATE);

INSERT INTO CALBOARD
VALUES(CALBOARDSEQ.NEXTVAL,'1','Kh정보교육ㄴㅇㄹㄴㄹ','어로나올ㄴ아ㅓㅗ','20201101',SYSDATE);
SELECT CAL_NO,USER_NO , CAL_TITLE, CAL_CONTENT, CAL_MDATE, CAL_REGDATE
				FROM CALBOARD 
				WHERE USER_NO = 1
				AND SUBSTR(CAL_MDATE,1,8) = '2020111'
				ORDER BY CAL_NO DESC

DELETE FROM CALBOARD



		SELECT CAL_NO,USER_NO, CAL_TITLE, CAL_CONTENT, CAL_MDATE, CAL_REGDATE,USER_NAME
					  FROM 
				(SELECT (ROW_NUMBER() OVER (PARTITION BY SUBSTR(CAL_MDATE,1,8) ORDER BY CAL_MDATE))RN, 
					  CALBOARD.CAL_NO,
					  CALBOARD.USER_NO,
					  CALBOARD.CAL_TITLE ,
					  CALBOARD.CAL_CONTENT, 
					  CALBOARD.CAL_MDATE,
					  CALBOARD.CAL_REGDATE,
					  USER_INFO.USER_NAME
					  FROM CALBOARD
					  JOIN USER_INFO ON CALBOARD.USER_NO = USER_INFO.USER_NO
					  WHERE CALBOARD.USER_NO = 1	
					  AND SUBSTR(CAL_MDATE,1,6)= '20201113' ) 
				      WHERE RN BETWEEN 1 AND 3;
				     
				      
				     
				    
SELECT *
FROM CALBOARD 


INSERT INTO USER_INFO
VALUES(,'')
			      
SELECT (ROW_NUMBER() OVER (PARTITION BY SUBSTR(CAL_MDATE,1,8) ORDER BY CAL_MDATE))AS RN,
					  CALBOARD.CAL_NO,
					  CALBOARD.USER_NO,
					  CALBOARD.CAL_TITLE,
					  CALBOARD.CAL_CONTENT, 
					  CALBOARD.CAL_MDATE,
					  CALBOARD.CAL_REGDATE
					  
					  FROM CALBOARD 
					  JOIN USER_INFO ON CALBOARD.USER_NO = USER_INFO.USER_NO
					  WHERE CALBOARD.USER_NO = 1							
					  AND SUBSTR(CAL_MDATE,1,6)= '20201113'
				      AND RN BETWEEN 1 AND 3;
				      				      
				      
				      
				      

				      
				      
				SELECT COUNT(*) 
				FROM CALBOARD 
				JOIN USER_INFO ON USER_INFO.USER_NO = CALBOARD.USER_NO
				WHERE CALBOARD.USER_NO = 1
				AND SUBSTR(CAL_MDATE,1 , 8) = '20201113' 
				      
DELETE FROM CALBOARD
WHERE USER_NO = 3
				
SELECT CAL_NO, USER_NO, CAL_TITLE, CAL_CONTENT, CAL_MDATE, CAL_REGDATE
					  FROM 
				(SELECT (ROW_NUMBER() OVER (PARTITION BY SUBSTR(CAL_MDATE,1,8) ORDER BY CAL_MDATE))RN, 
					  CAL_NO,
					  USER_NO ,
					  CAL_TITLE ,
					  CAL_CONTENT, 
					  CAL_MDATE,
					  CAL_REGDATE
					  FROM CALBOARD 
					  WHERE USER_NO = 3	
					  							
					  AND SUBSTR(CAL_MDATE,1,8)= '20201114' )  
				      WHERE RN BETWEEN 1 AND 3				

				      
	 	SELECT CAL_NO,USER_NO , CAL_TITLE, CAL_CONTENT, CAL_MDATE, CAL_REGDATE
				FROM CALBOARD 
				WHERE USER_NO = 3
				AND SUBSTR(CAL_MDATE,1,8) = '20201115'
				
			      
				  
				      
				      
				      
				      
				      
