DROP SEQUENCE FILE_UPLOAD_SEQ;
DROP TABLE FILE_UPLOAD;
CREATE SEQUENCE FILE_UPLOAD_SEQ;
CREATE TABLE FILE_UPLOAD(
	FILE_NO NUMBER PRIMARY KEY,
	USER_NO NUMBER NOT NULL,
	FILE_NAME VARCHAR2(4000) NOT NULL, -- FILE_TITLE? FILE_NAME?
	FILE_TYPE VARCHAR2(20) NOT NULL, -- 1-[1]-(2)로 인해 프로필 사진은 USER_INFO 테이블만 사용한다면 제외
	FILE_REGDATE DATE NOT NULL,
	CONSTRAINTS FILE_UPLOAD_UN_FK FOREIGN KEY (USER_NO) REFERENCES USER_INFO(USER_NO),
	CONSTRAINTS FILE_TYPE_CK CHECK(FILE_TYPE IN ('I','V')) -- IMAGE, VIDEO
);
-- BLOB? CLOB? NCLOB?

SELECT FILE_NO, USER_NO, FILE_NAME, FILE_TYPE, FILE_REGDATE
FROM FILE_UPLOAD;