select object_name, object_type from user_objects

----------------------------

DROP SEQUENCE USER_TODO_SEQ;
DROP TABLE USER_TODO;

CREATE SEQUENCE USER_TODO_SEQ;
CREATE TABLE USER_TODO(
	TODO_NO NUMBER PRIMARY KEY,
	USER_NO NUMBER NOT NULL,
	TODO_TITLE VARCHAR2(4000) NOT NULL,
	TODO_COLOR VARCHAR2(1000) NOT NULL,
	TODO_CONTENT VARCHAR2(4000),
	TODO_CATEGORY VARCHAR2(4000),
	TODO_HASHTAG VARCHAR2(4000),
	TODO_DATE DATE NOT NULL,
	TODO_COMPLETE VARCHAR(100) NOT NULL,
	TODO_STARTTIME DATE,
	TODO_ENDTIME DATE,
	CONSTRAINT USER_TODO_UN_FK FOREIGN KEY(USER_NO) REFERENCES USER_INFO(USER_NO),
	CONSTRAINT USER_TODO_COMPLETE_CK CHECK(TODO_COMPLETE IN ('Y','N'))
);
	
SELECT TODO_NO, USER_NO, TODO_TITLE, TODO_COLOR, TODO_CONTENT,
TODO_CATEGORY, TODO_HASHTAG, TODO_DATE, TODO_COMPLETE, TODO_STARTTIME, TODO_ENDTIME
FROM USER_TODO;

SELECT TODO_NO, REPLACE(TODO_HASHTAG, '\00A0', ' ') AS TODO_HASHTAG, 
REPLACE(TODO_HASHTAG, ' ', '^') AS TODO_TAG2
FROM USER_TODO
WHERE TODO_NO = 5;

select * from user_todo;
select * from user_info;

select * from user_todo where user_no=3;

select todo_no, todo_title, todo_starttime, todo_endtime
from user_todo
where user_no = 5
order by todo_no;

SELECT TODO_NO, USER_NO, TODO_TITLE, TODO_COLOR, TODO_CONTENT, TODO_CATEGORY,
TODO_HASHTAG, TODO_DATE, TODO_COMPLETE, TODO_STARTTIME, TODO_ENDTIME
FROM USER_TODO
WHERE USER_NO = 5
ORDER BY TODO_STARTTIME, TODO_NO

--DROP SEQUENCE STOPWATCH_SEQ;
--DROP TABLE STOPWATCH;
--
---- STOPWATCH? TIME? WHAT IS BETTER???
--CREATE SEQUENCE STOPWATCH_SEQ;
--CREATE TABLE STOPWATCH( 
--	STOPWATCH_NO NUMBER PRIMARY KEY,
--	TODO_NO NUMBER NOT NULL,
--	START_TIME DATE NOT NULL,
--	END_TIME DATE NOT NULL,
--	CONSTRAINT STOPWATCH_TN_FK FOREIGN KEY(TODO_NO) REFERENCES USER_TODO(TODO_NO)
--);

------------------
------------------
--weekly 테스트---
SELECT * FROM USER_TODO
WHERE USER_NO = 3;

SELECT 
LISTAGG(THE_DATE, ', ') WITHIN GROUP(ORDER BY THE_DATE) "THE_DATE",
LISTAGG(FULLCOUNT, ', ') WITHIN GROUP(ORDER BY THE_DATE) "FULLCOUNT",
LISTAGG(COMPLETE, ', ') WITHIN GROUP(ORDER BY THE_DATE) "COMPLETE",
LISTAGG(UNCOMPLETE, ', ') WITHIN GROUP(ORDER BY THE_DATE) "UNCOMPLETE"
FROM (
SELECT TO_CHAR((SYSDATE - 6),'YYYYMMDD') the_date, FULLCOUNT, COMPLETE, FULLCOUNT-COMPLETE AS UNCOMPLETE
FROM (SELECT COUNT(*) FULLCOUNT FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE - 6),'YYYYMMDD')) A,
(SELECT COUNT(*) COMPLETE FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE - 6),'YYYYMMDD')
AND TODO_COMPLETE = 'Y') B 
UNION ALL 
SELECT TO_CHAR((SYSDATE - 6),'YYYYMMDD') the_date, 0 AS FULLCOUNT, 0 AS COMPLETE, 0 AS UNCOMPLETE
FROM DUAL
WHERE NOT EXISTS (SELECT TO_CHAR((SYSDATE - 6),'YYYYMMDD') the_date, FULLCOUNT, COMPLETE, FULLCOUNT-COMPLETE AS UNCOMPLETE
FROM (SELECT COUNT(*) FULLCOUNT FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE - 6),'YYYYMMDD')) A,
(SELECT COUNT(*) COMPLETE FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE - 6),'YYYYMMDD')
AND TODO_COMPLETE = 'Y') B )
UNION 
SELECT TO_CHAR((SYSDATE - 5),'YYYYMMDD') the_date, FULLCOUNT, COMPLETE, FULLCOUNT-COMPLETE AS UNCOMPLETE
FROM (SELECT COUNT(*) FULLCOUNT FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE - 5),'YYYYMMDD')) A,
(SELECT COUNT(*) COMPLETE FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE - 5),'YYYYMMDD')
AND TODO_COMPLETE = 'Y') B 
UNION ALL 
SELECT TO_CHAR((SYSDATE - 5),'YYYYMMDD') the_date, 0 AS FULLCOUNT, 0 AS COMPLETE, 0 AS UNCOMPLETE
FROM DUAL
WHERE NOT EXISTS (SELECT TO_CHAR((SYSDATE - 5),'YYYYMMDD') the_date, FULLCOUNT, COMPLETE, FULLCOUNT-COMPLETE AS UNCOMPLETE
FROM (SELECT COUNT(*) FULLCOUNT FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE - 5),'YYYYMMDD')) A,
(SELECT COUNT(*) COMPLETE FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE - 5),'YYYYMMDD')
AND TODO_COMPLETE = 'Y') B )
UNION 
SELECT TO_CHAR((SYSDATE - 4),'YYYYMMDD') the_date, FULLCOUNT, COMPLETE, FULLCOUNT-COMPLETE AS UNCOMPLETE
FROM (SELECT COUNT(*) FULLCOUNT FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE - 4),'YYYYMMDD')) A,
(SELECT COUNT(*) COMPLETE FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE - 4),'YYYYMMDD')
AND TODO_COMPLETE = 'Y') B 
UNION ALL 
SELECT TO_CHAR((SYSDATE - 6),'YYYYMMDD') the_date, 0 AS FULLCOUNT, 0 AS COMPLETE, 0 AS UNCOMPLETE
FROM DUAL
WHERE NOT EXISTS (SELECT TO_CHAR((SYSDATE - 4),'YYYYMMDD') the_date, FULLCOUNT, COMPLETE, FULLCOUNT-COMPLETE AS UNCOMPLETE
FROM (SELECT COUNT(*) FULLCOUNT FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE - 4),'YYYYMMDD')) A,
(SELECT COUNT(*) COMPLETE FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE - 4),'YYYYMMDD')
AND TODO_COMPLETE = 'Y') B )
UNION 
SELECT TO_CHAR((SYSDATE - 3),'YYYYMMDD') the_date, FULLCOUNT, COMPLETE, FULLCOUNT-COMPLETE AS UNCOMPLETE
FROM (SELECT COUNT(*) FULLCOUNT FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE - 3),'YYYYMMDD')) A,
(SELECT COUNT(*) COMPLETE FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE - 3),'YYYYMMDD')
AND TODO_COMPLETE = 'Y') B 
UNION ALL 
SELECT TO_CHAR((SYSDATE - 3),'YYYYMMDD') the_date, 0 AS FULLCOUNT, 0 AS COMPLETE, 0 AS UNCOMPLETE
FROM DUAL
WHERE NOT EXISTS (SELECT TO_CHAR((SYSDATE - 3),'YYYYMMDD') the_date, FULLCOUNT, COMPLETE, FULLCOUNT-COMPLETE AS UNCOMPLETE
FROM (SELECT COUNT(*) FULLCOUNT FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE - 3),'YYYYMMDD')) A,
(SELECT COUNT(*) COMPLETE FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE - 3),'YYYYMMDD')
AND TODO_COMPLETE = 'Y') B )
UNION 
SELECT TO_CHAR((SYSDATE - 2),'YYYYMMDD') the_date, FULLCOUNT, COMPLETE, FULLCOUNT-COMPLETE AS UNCOMPLETE
FROM (SELECT COUNT(*) FULLCOUNT FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE - 2),'YYYYMMDD')) A,
(SELECT COUNT(*) COMPLETE FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE - 2),'YYYYMMDD')
AND TODO_COMPLETE = 'Y') B 
UNION ALL 
SELECT TO_CHAR((SYSDATE - 2),'YYYYMMDD') the_date, 0 AS FULLCOUNT, 0 AS COMPLETE, 0 AS UNCOMPLETE
FROM DUAL
WHERE NOT EXISTS (SELECT TO_CHAR((SYSDATE - 2),'YYYYMMDD') the_date, FULLCOUNT, COMPLETE, FULLCOUNT-COMPLETE AS UNCOMPLETE
FROM (SELECT COUNT(*) FULLCOUNT FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE - 2),'YYYYMMDD')) A,
(SELECT COUNT(*) COMPLETE FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE - 2),'YYYYMMDD')
AND TODO_COMPLETE = 'Y') B )
UNION 
SELECT TO_CHAR((SYSDATE - 1),'YYYYMMDD') the_date, FULLCOUNT, COMPLETE, FULLCOUNT-COMPLETE AS UNCOMPLETE
FROM (SELECT COUNT(*) FULLCOUNT FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE - 1),'YYYYMMDD')) A,
(SELECT COUNT(*) COMPLETE FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE - 1),'YYYYMMDD')
AND TODO_COMPLETE = 'Y') B 
UNION ALL 
SELECT TO_CHAR((SYSDATE - 1),'YYYYMMDD') the_date, 0 AS FULLCOUNT, 0 AS COMPLETE, 0 AS UNCOMPLETE
FROM DUAL
WHERE NOT EXISTS (SELECT TO_CHAR((SYSDATE - 1),'YYYYMMDD') the_date, FULLCOUNT, COMPLETE, FULLCOUNT-COMPLETE AS UNCOMPLETE
FROM (SELECT COUNT(*) FULLCOUNT FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE - 1),'YYYYMMDD')) A,
(SELECT COUNT(*) COMPLETE FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE - 1),'YYYYMMDD')
AND TODO_COMPLETE = 'Y') B )
UNION 
SELECT TO_CHAR((SYSDATE),'YYYYMMDD') the_date, FULLCOUNT, COMPLETE, FULLCOUNT-COMPLETE AS UNCOMPLETE
FROM (SELECT COUNT(*) FULLCOUNT FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE),'YYYYMMDD')) A,
(SELECT COUNT(*) COMPLETE FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE),'YYYYMMDD')
AND TODO_COMPLETE = 'Y') B 
UNION ALL 
SELECT TO_CHAR((SYSDATE),'YYYYMMDD') the_date, 0 AS FULLCOUNT, 0 AS COMPLETE, 0 AS UNCOMPLETE
FROM DUAL
WHERE NOT EXISTS (SELECT TO_CHAR((SYSDATE),'YYYYMMDD') the_date, FULLCOUNT, COMPLETE, FULLCOUNT-COMPLETE AS UNCOMPLETE
FROM (SELECT COUNT(*) FULLCOUNT FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE),'YYYYMMDD')) A,
(SELECT COUNT(*) COMPLETE FROM USER_TODO 
WHERE USER_NO = 3
AND TO_CHAR(TODO_DATE, 'YYYYMMDD') =  TO_CHAR((SYSDATE),'YYYYMMDD')
AND TODO_COMPLETE = 'Y') B )
)


